'use client';
import { FormEvent, useEffect, useRef, useState } from 'react';
import { localizeElement, Language } from '@/lib/i18n';

export default function Login(){
 const [username,setU]=useState('dpo'); const [password,setP]=useState('Dpo@12345'); const [error,setE]=useState(''); const [busy,setB]=useState(false);const [language,setLanguage]=useState<Language>('en');const [mfaChallenge,setMfaChallenge]=useState('');const [mfaCode,setMfaCode]=useState('');const languageRoot=useRef<HTMLElement>(null);
 useEffect(()=>{localStorage.removeItem('dpo_preview_token')},[]);
 useEffect(()=>{const saved=localStorage.getItem('dpo_language');if(saved==='ur')setLanguage('ur')},[]);
 useEffect(()=>{const root=languageRoot.current;if(!root)return;document.documentElement.lang=language==='ur'?'ur':'en';document.documentElement.dir='ltr';root.dataset.language=language;localizeElement(root,language);const observer=new MutationObserver(()=>localizeElement(root,language));observer.observe(root,{childList:true,subtree:true,characterData:true});return()=>observer.disconnect()},[language]);
 function toggleLanguage(){const next:Language=language==='en'?'ur':'en';setLanguage(next);localStorage.setItem('dpo_language',next)}
 function finishLogin(j:any){if(j.preview_token){localStorage.setItem('dpo_preview_token',j.preview_token);window.location.assign(`/portal?auth=${encodeURIComponent(j.preview_token)}`)}else window.location.assign('/portal')}
 async function submit(e:FormEvent){e.preventDefault();setB(true);setE('');try{const r=await fetch('/api/auth/login',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({username,password})});const text=await r.text();const j=text?JSON.parse(text):{};if(!r.ok){setB(false);setE(j.error||'Login failed');return}if(j.mfa_required){setMfaChallenge(j.challenge_token||'');setMfaCode('');setB(false);return}finishLogin(j)}catch{setB(false);setE('Connection error. Please try again.')}}
 async function verifyMfa(e:FormEvent){e.preventDefault();setB(true);setE('');try{const r=await fetch('/api/auth/2fa/verify',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({challenge_token:mfaChallenge,code:mfaCode})});const text=await r.text();const j=text?JSON.parse(text):{};if(!r.ok){setB(false);setE(j.error||'Authenticator verification failed');return}finishLogin(j)}catch{setB(false);setE('Connection error. Please try again.')}}
 return <main ref={languageRoot} className="login-page" data-language={language}><section className="login-brand"><div className="seal">IT</div><p>GOVERNMENT OF PUNJAB</p><h1>DPO Digital Dak<br/>& File Management System</h1><p className="muted-light">Secure • Traceable • Accountable</p><div className="security-note">🔒 Authorized office personnel only. All access and actions are logged.</div></section><section className="login-panel"><button type="button" className="language-toggle login-language-toggle" onClick={toggleLanguage} data-no-translate>{language==='en'?'اردو':'English'}</button><form className="login-card" onSubmit={mfaChallenge?verifyMfa:submit}>{mfaChallenge?<><p className="eyebrow">SECOND FACTOR</p><h2>Two-factor verification</h2><p className="sub">Open your authenticator app and enter the 6-digit code.</p>{error&&<div className="alert error">{error}</div>}<label>Authenticator code<input value={mfaCode} onChange={e=>setMfaCode(e.target.value.replace(/\D/g,'').slice(0,6))} inputMode="numeric" pattern="[0-9]{6}" autoComplete="one-time-code" autoFocus required/></label><button className="primary wide" disabled={busy}>{busy?'Verifying…':'Verify code →'}</button><button type="button" className="secondary wide login-back" onClick={()=>{setMfaChallenge('');setMfaCode('');setE('')}} disabled={busy}>Use password again</button></>:<><div className="mobile-seal">IT</div><p className="eyebrow">SECURE ACCESS</p><h2>Sign in to your account</h2><p className="sub">Enter your official credentials to continue.</p>{error&&<div className="alert error">{error}</div>}<label>Username<input value={username} onChange={e=>setU(e.target.value)} autoComplete="username" required/></label><label>Password<input type="password" value={password} onChange={e=>setP(e.target.value)} autoComplete="current-password" required/></label><button className="primary wide" disabled={busy}>{busy?'Verifying…':'Sign in securely →'}</button><div className="demo-box"><b>Prototype accounts</b><span>DPO: dpo / Dpo@12345</span><span>Clerk: clerk / Clerk@12345</span><span>Admin: admin / Admin@12345</span><span>Branch Head: head.ops / Branch@12345</span></div><small>By signing in, you acknowledge that activity is monitored and audited.</small></>}</form></section></main>
}
